USE MARVEL;
DELIMITER $$
CREATE FUNCTION UDF_GET_MOVIE_BUDGET_LEVEL(MOVIE_BUDGET DECIMAL(15,2))
RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
    DECLARE BUDGET_LEVEL VARCHAR(10);
    IF MOVIE_BUDGET < 100000000 THEN
        SET BUDGET_LEVEL = 'Нисък';
    ELSEIF MOVIE_BUDGET BETWEEN 100000000 AND 200000000 THEN
        SET BUDGET_LEVEL = 'Стандартен';
    ELSE
        SET BUDGET_LEVEL = 'Висок';
    END IF;
    RETURN BUDGET_LEVEL;
END $$
DELIMITER ;

DELIMITER $$

CREATE FUNCTION UDF_GET_OVER_BUDGET_DATE(MOVIE_ID INT)
RETURNS DATE
DETERMINISTIC
BEGIN
    DECLARE OVER_BUDGET_DATE DATE;
    SELECT MIN(SCREENING_DATE)
    INTO OVER_BUDGET_DATE
    FROM MARVEL_MOVIE_PREMIERE_SCREENINGS S
    INNER JOIN MARVEL_MOVIES M ON S.MOVIE_ID = M.MOVIE_ID
    WHERE S.MOVIE_ID = MOVIE_ID AND S.DAILY_BOX_OFFICE > M.MOVIE_BUDGET;
    RETURN OVER_BUDGET_DATE;
END $$

DELIMITER ;

DELIMITER $$

CREATE FUNCTION UDF_GET_MOST_POPULAR_POWER(HERO_ID INT)
RETURNS VARCHAR(100)
DETERMINISTIC
BEGIN
    DECLARE MOST_POPULAR_POWER VARCHAR(100);

    SELECT POWER_NAME
    INTO MOST_POPULAR_POWER
    FROM MARVEL_HERO_POWERS
    WHERE HERO_ID = HERO_ID
    LIMIT 1;
	RETURN MOST_POPULAR_POWER;
END $$

DELIMITER ;

DELIMITER $$

CREATE FUNCTION UDF_TOTAL_BOX_OFFICE_BY_HERO(HERO_ID INT)
RETURNS DECIMAL(15,2)
DETERMINISTIC
BEGIN
    DECLARE TOTAL_BOX_OFFICE DECIMAL(15,2);
    SELECT SUM(M.MOVIE_BOX_OFFICE)
    INTO TOTAL_BOX_OFFICE
    FROM MARVEL_HERO_MOVIES HM
    INNER JOIN MARVEL_MOVIES M ON HM.MOVIE_ID = M.MOVIE_ID
    WHERE HM.HERO_ID = HERO_ID;
    RETURN IFNULL(TOTAL_BOX_OFFICE, 0); 
END $$

DELIMITER ;
