START TRANSACTION; 

INSERT INTO MARVEL_HEROES (HERO_ID, HERO_NAME, HERO_REAL_NAME, HERO_ORIGIN, HERO_FIRST_APPEARENCE, HERO_PLANET, HERO_AGE) 
VALUES (36, 'Black Knight', 'Dane Whitman', 'England', 1967, 'Earth', 35);

INSERT INTO MARVEL_MOVIES (MOVIE_ID, MOVIE_TITLE, MOVIE_RELEASE_DATE, MOVIE_RATING, MOVIE_BUDGET, MOVIE_BOX_OFFICE)
VALUES (21, 'The Black Knight', '2025-05-05', 7, 150000000, 300000000);

INSERT INTO MARVEL_HERO_MOVIES (HERO_ID, MOVIE_ID) 
VALUES (36, 21);
COMMIT;
ROLLBACK;
